---
argo-cd:
  namespaceOverride: argo-cd
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false

  global:
    domain: argocd.arkhamasylum.xyz

  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: nginx
      tls: false
